name: CD

on:
  push:
    tags: 
      - '**'

env:
  CLIENT_PATH: ./AutoEmptyStandbyList.Client
  UNINSTALLER_PATH: ./AutoEmptyStandbyList.Uninstaller

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Clean Solution
      run: dotnet clean

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: |
        dotnet publish ${{ env.CLIENT_PATH }} -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o /publish/client
        dotnet publish ${{ env.UNINSTALLER_PATH }} -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o /publish/uninstall
    
    - name: Copy additional files
      run: |
        mkdir /Release/scripts
        cp ./Scripts/* /Release/scripts/
        cp /publish/client/AutoEmptyStandbyList.exe /Release/AutoEmptyStandbyList.exe
        cp /publish/uninstall/AutoEmptyStandbyList.Uninstaller.exe /Release/AutoEmptyStandbyList.Uninstaller.exe

    - name: Zip files
      run: Compress-Archive -Path /Release/* -Destination Release.zip 

    - name: Create or Update Release
      uses: ColinPitrat/update-release@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./Release.zip